apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: shared-todo
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todo
          image: thepapermen/devopswithkubernetes:todo-0.2.0-slim
          volumeMounts:
            - name: shared-todo
              mountPath: /usr/src/app/files
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
            - name: IMAGE_LIFE_MINUTES
              value: "0.1"
            - name: MEDIA_ROOT
              value: "/usr/src/app/files/"
