apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: todo-pv-class # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Mi
