apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: thepapermen/devopswithkubernetes:todo-0.1.2-slim
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
