[tool.poetry]
name = "todo"
version = "0.1.0"
description = "Project for the course DevopsWithKubernetes"
authors = ["Ivan Kharlamov <the.paper.men@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.4"

